---
- hosts: localhost
  connection: local
  become: true

  
  tasks:
  
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"

  - name: install apps via apt
    apt:
      name:
      - htop
      - ncdu
      - zsh
      - git
      - mc
      - tmux
      - tldr
      state: present
