---
- hosts: localhost
  connection: local
  become: true

  
  pre_tasks:
    - name: update and upgrade debian repositories
      apt:
        update_cache: yes
        upgrade: yes

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml

