---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install apps via apt
    apt:
      name:
      - htop
      - ncdu
      - zsh
      - git
      - mc
      - tmux
      - tldr
      state: present
