- name: copy zsh config files to user home directory
  copy:
    src: files/zsh/
    dest: ~/
    owner: $(whoami)
    group: $(whoami)
    mode: 0644

- name: restart zsh shell
  shell:
    cmd: 'exec zsh -l'